import { Generator } from "@jspm/generator";
import assert from "assert";
import { SemverRange } from "sver";

let generator = new Generator({
  rootUrl: new URL("./local", import.meta.url),
  env: ["production", "browser"],
  resolutions: {
    react: "17",
  },
});

const esmsPkg = await generator.traceMap.resolver.resolveLatestTarget(
  { name: "es-module-shims", registry: "npm", ranges: [new SemverRange("*")] },
  generator.traceMap.installer.defaultProvider
);

const esmsUrl =
  (await generator.traceMap.resolver.pkgToUrl(
    esmsPkg,
    generator.traceMap.installer.defaultProvider
  )) + "dist/es-module-shims.js";

async function checkIndent(html, expected) {
  generator = new Generator({
    rootUrl: new URL("./local", import.meta.url),
    env: ["production", "browser"],
    resolutions: {
      react: "17",
    },
  });

  const res = await generator.htmlGenerate(html, {
    preload: true,
  });

  assert.strictEqual(res.trim(), expected.trim());
}

// Existing import map in tag:
await checkIndent(
  `
<!doctype html>
  <script type="importmap">
  {
    "imports": {
      "object-assign": "/react.js"
    }
  }
  </script>
<script type="module">
  import 'react';
</script>
`,
  `
<!doctype html>
  <!-- Generated by @jspm/generator - https://github.com/jspm/generator -->
  <script async src="${esmsUrl}" crossorigin="anonymous"></script>
  <script type="importmap">
  {
    "imports": {
      "object-assign": "/react.js",
      "react": "https://ga.jspm.io/npm:react@17.0.2/index.js"
    }
  }
  </script>
  <link rel="modulepreload" href="/react.js" />
  <link rel="modulepreload" href="https://ga.jspm.io/npm:react@17.0.2/index.js" />
<script type="module">
  import 'react';
</script>
`
);

// Existing empty tag:
await checkIndent(
  `
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>JSPM example</title>
    <script type="importmap"></script>
  </head>
  <body>
    <script type="module">
      import 'react';
    </script>
  </body>
</html>`,
  `
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>JSPM example</title>
    <!-- Generated by @jspm/generator - https://github.com/jspm/generator -->
    <script async src="${esmsUrl}" crossorigin="anonymous"></script>
    <script type="importmap">
    {
      "imports": {
        "react": "https://ga.jspm.io/npm:react@17.0.2/index.js"
      },
      "scopes": {
        "https://ga.jspm.io/": {
          "object-assign": "https://ga.jspm.io/npm:object-assign@4.1.1/index.js"
        }
      }
    }
    </script>
    <link rel="modulepreload" href="https://ga.jspm.io/npm:object-assign@4.1.1/index.js" />
    <link rel="modulepreload" href="https://ga.jspm.io/npm:react@17.0.2/index.js" />
  </head>
  <body>
    <script type="module">
      import 'react';
    </script>
  </body>
</html>
`
);

// No existing tag, but a script in the body:
await checkIndent(
  `
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>JSPM example</title>
  </head>
  <body>
    <script type="module">
      import 'react';
    </script>
  </body>
</html>`,
  `
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>JSPM example</title>
  </head>
  <body>
    <!-- Generated by @jspm/generator - https://github.com/jspm/generator -->
    <script async src="https://ga.jspm.io/npm:es-module-shims@1.7.0/dist/es-module-shims.js" crossorigin="anonymous"></script>
    <script type="importmap">
    {
      "imports": {
        "react": "https://ga.jspm.io/npm:react@17.0.2/index.js"
      },
      "scopes": {
        "https://ga.jspm.io/": {
          "object-assign": "https://ga.jspm.io/npm:object-assign@4.1.1/index.js"
        }
      }
    }
    </script>
    <link rel="modulepreload" href="https://ga.jspm.io/npm:object-assign@4.1.1/index.js" />
    <link rel="modulepreload" href="https://ga.jspm.io/npm:react@17.0.2/index.js" />
    <script type="module">
      import 'react';
    </script>
  </body>
</html>
`
);

// No existing tag and no scripts:
await checkIndent(
  `
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>JSPM example</title>
  </head>
  <body>
  </body>
</html>`,
  `
<!DOCTYPE html>
<html>
  <head>
    <!-- Generated by @jspm/generator - https://github.com/jspm/generator -->
    <script async src="https://ga.jspm.io/npm:es-module-shims@1.7.0/dist/es-module-shims.js" crossorigin="anonymous"></script>
    <script type="importmap">
    {}
    </script>
    <meta charset="utf-8">
    <title>JSPM example</title>
  </head>
  <body>
  </body>
</html>
`
);
