import { Generator } from "@jspm/generator";
import assert from "assert";
import { SemverRange } from "sver";

const generator = new Generator({
  rootUrl: new URL("./local", import.meta.url),
  env: ["production", "browser"],
  resolutions: {
    react: "17",
  },
});

const esmsPkg = await generator.traceMap.resolver.resolveLatestTarget(
  { name: "es-module-shims", registry: "npm", ranges: [new SemverRange("*")] },
  generator.traceMap.installer.defaultProvider
);
const esmsUrl =
  generator.traceMap.resolver.pkgToUrl(
    esmsPkg,
    generator.traceMap.installer.defaultProvider
  ) + "dist/es-module-shims.js";

assert.strictEqual(
  await generator.htmlGenerate(
    `
<!doctype html>
  <script type="importmap">
  {
    "imports": {
      "object-assign": "/react.js"
    }
  }
  </script>
<script type="module">
  import 'react';
</script>
`,
    { preload: true }
  ),
  "\n" +
    "<!doctype html>\n" +
    "  <!-- Generated by @jspm/generator - https://github.com/jspm/generator -->\n" +
    `  <script async src="${esmsUrl}" crossorigin="anonymous"></script>\n` +
    '  <script type="importmap">\n' +
    "  {\n" +
    '    "imports": {\n' +
    '      "object-assign": "/react.js",\n' +
    '      "react": "https://ga.jspm.io/npm:react@17.0.2/index.js"\n' +
    "    }\n" +
    "  }\n" +
    "  </script>\n" +
    '  <link rel="modulepreload" href="/react.js" />\n' +
    '  <link rel="modulepreload" href="https://ga.jspm.io/npm:react@17.0.2/index.js" />\n' +
    '<script type="module">\n' +
    "  import 'react';\n" +
    "</script>\n"
);
