import { Generator } from "@jspm/generator";
import assert from "assert";
import { SemverRange } from "sver";

const generator = new Generator({
  rootUrl: new URL("./local", import.meta.url),
  env: ["production", "browser"],
  resolutions: {
    react: "17",
  },
});

const esmsPkg = await generator.traceMap.resolver.resolveLatestTarget(
  { name: "es-module-shims", registry: "npm", ranges: [new SemverRange("*")] },
  generator.traceMap.installer.defaultProvider
);
const esmsUrl =
  (await generator.traceMap.resolver.pkgToUrl(
    esmsPkg,
    generator.traceMap.installer.defaultProvider
  )) + "dist/es-module-shims.js";

const html = `<!DOCTYPE html>

<script type="module">
    import "react";
</script>

<body>
    <script type="text/plain">
        Hello World
    </script>
</body>`;

const pins = await generator.addMappings(html);

assert.strictEqual(await generator.htmlInject(html, { pins, preload: true }), 
  "<!DOCTYPE html>\n" +
    "\n" +
    "<!-- Generated by @jspm/generator - https://github.com/jspm/generator -->\n" +
    `<script async src="${esmsUrl}" crossorigin="anonymous"></script>\n` +
    '<script type="importmap">\n' +
    "{\n" +
    '  "imports": {\n' +
    '    "react": "https://ga.jspm.io/npm:react@17.0.2/index.js"\n' +
    "  },\n" +
    '  "scopes": {\n' +
    '    "https://ga.jspm.io/": {\n' +
    '      "object-assign": "https://ga.jspm.io/npm:object-assign@4.1.1/index.js"\n' +
    "    }\n" +
    "  }\n" +
    "}\n" +
    "</script>\n" +
    '<link rel="modulepreload" href="https://ga.jspm.io/npm:object-assign@4.1.1/index.js" />\n' +
    '<link rel="modulepreload" href="https://ga.jspm.io/npm:react@17.0.2/cjs/react.production.min.js" />\n' +
    '<link rel="modulepreload" href="https://ga.jspm.io/npm:react@17.0.2/index.js" />\n' +
    '<script type="module">\n' +
    '    import "react";\n' +
    "</script>\n" +
    "\n" +
    "<body>\n" +
    '    <script type="text/plain">\n' +
    "        Hello World\n" +
    "    </script>\n" +
    "</body>"
);
