import { Generator } from "@jspm/generator";
import assert from "assert";
import { SemverRange } from "sver";

/*
 * Multi-HTML workflow example
 *
 * Primary HTML page is used as the main map and lockfile
 *
 * We then create a new HTML page extracting only the necessary mappings
 * for the modules on this page
 */

const primaryHtml = `<!doctype html>
<script type="importmap">
{
  "imports": {
    "lit": "https://ga.jspm.io/npm:lit@2.2.7/index.js",
    "lit/decorators/property.js": "https://ga.jspm.io/npm:lit@2.2.7/decorators/property.js",
    "lit/directives/async-append.js": "https://ga.jspm.io/npm:lit@2.2.7/directives/async-append.js",
    "lit/directives/guard.js": "https://ga.jspm.io/npm:lit@2.2.7/directives/guard.js"
  },
  "scopes": {
    "https://ga.jspm.io/": {
      "@lit/reactive-element": "https://ga.jspm.io/npm:@lit/reactive-element@1.3.2/reactive-element.js",
      "@lit/reactive-element/decorators/property.js": "https://ga.jspm.io/npm:@lit/reactive-element@1.3.2/decorators/property.js",
      "lit-element/lit-element.js": "https://ga.jspm.io/npm:lit-element@3.2.1/lit-element.js",
      "lit-html": "https://ga.jspm.io/npm:lit-html@2.2.6/lit-html.js",
      "lit-html/directives/async-append.js": "https://ga.jspm.io/npm:lit-html@2.2.6/directives/async-append.js",
      "lit-html/directives/guard.js": "https://ga.jspm.io/npm:lit-html@2.2.6/directives/guard.js"
    }
  }
}
</script>
`;

const generator = new Generator({
  inputMap: primaryHtml,
  mapUrl: new URL("./index.html", import.meta.url),
  rootUrl: new URL("./local", import.meta.url),
  env: ["production", "browser"],
});

const esmsPkg = await generator.traceMap.resolver.resolveLatestTarget(
  { name: "es-module-shims", registry: "npm", ranges: [new SemverRange("*")] },
  generator.traceMap.installer.defaultProvider
);
const esmsUrl =
  (await generator.traceMap.resolver.pkgToUrl(
    esmsPkg,
    generator.traceMap.installer.defaultProvider
  )) + "dist/es-module-shims.js";

await generator.link("lit/html.js");

const primaryHtmlProcessed = await generator.htmlInject(primaryHtml);

assert.strictEqual(
  primaryHtmlProcessed,
  `<!doctype html>
<!-- Generated by @jspm/generator - https://github.com/jspm/generator -->
<script async src="${esmsUrl}" crossorigin="anonymous"></script>
<script type="importmap">
{
  "imports": {
    "lit": "https://ga.jspm.io/npm:lit@2.2.7/index.js",
    "lit/decorators/property.js": "https://ga.jspm.io/npm:lit@2.2.7/decorators/property.js",
    "lit/directives/async-append.js": "https://ga.jspm.io/npm:lit@2.2.7/directives/async-append.js",
    "lit/directives/guard.js": "https://ga.jspm.io/npm:lit@2.2.7/directives/guard.js",
    "lit/html.js": "https://ga.jspm.io/npm:lit@2.2.7/html.js"
  },
  "scopes": {
    "https://ga.jspm.io/": {
      "@lit/reactive-element": "https://ga.jspm.io/npm:@lit/reactive-element@1.3.2/reactive-element.js",
      "@lit/reactive-element/decorators/property.js": "https://ga.jspm.io/npm:@lit/reactive-element@1.3.2/decorators/property.js",
      "lit-element/lit-element.js": "https://ga.jspm.io/npm:lit-element@3.2.1/lit-element.js",
      "lit-html": "https://ga.jspm.io/npm:lit-html@2.2.6/lit-html.js",
      "lit-html/directives/": "https://ga.jspm.io/npm:lit-html@2.2.6/directives/"
    }
  }
}
</script>
`
);

// Idempotence
{
  const generator = new Generator({
    inputMap: primaryHtmlProcessed,
    freeze: true,
    env: ["production", "browser"],
  });
  assert.strictEqual(
    await generator.htmlInject(primaryHtmlProcessed),
    primaryHtmlProcessed
  );
}

// Sub-page extraction where sub-page has a specific import path to preload
const subpageHtml = await generator.htmlInject(
  `<!doctype html>
<script type="module">
  import 'lit/directives/guard.js';
  import 'lit';
</script>
`,
  { trace: true }
);

assert.strictEqual(
  subpageHtml,
  `<!doctype html>
<!-- Generated by @jspm/generator - https://github.com/jspm/generator -->
<script async src="${esmsUrl}" crossorigin="anonymous"></script>
<script type="importmap">
{
  "imports": {
    "lit": "https://ga.jspm.io/npm:lit@2.2.7/index.js",
    "lit/directives/guard.js": "https://ga.jspm.io/npm:lit@2.2.7/directives/guard.js"
  },
  "scopes": {
    "https://ga.jspm.io/": {
      "@lit/reactive-element": "https://ga.jspm.io/npm:@lit/reactive-element@1.3.2/reactive-element.js",
      "lit-element/lit-element.js": "https://ga.jspm.io/npm:lit-element@3.2.1/lit-element.js",
      "lit-html": "https://ga.jspm.io/npm:lit-html@2.2.6/lit-html.js",
      "lit-html/directives/guard.js": "https://ga.jspm.io/npm:lit-html@2.2.6/directives/guard.js"
    }
  }
}
</script>
<script type="module">
  import 'lit/directives/guard.js';
  import 'lit';
</script>
`
);
