import { Generator } from "@jspm/generator";
import assert from "assert";
import { SemverRange } from "sver";
import { getIntegrity } from "../../lib/common/integrity.js";

const generator = new Generator({
  mapUrl: new URL("./local/page.html", import.meta.url),
  env: ["production", "browser"],
});

const esmsPkg = await generator.traceMap.resolver.resolveLatestTarget(
  { name: "es-module-shims", registry: "npm", ranges: [new SemverRange("*")] },
  generator.traceMap.installer.defaultProvider
);
const esmsUrl =
  (await generator.traceMap.resolver.pkgToUrl(
    esmsPkg,
    generator.traceMap.installer.defaultProvider
  )) + "dist/es-module-shims.js";
const esmsIntegrity = await getIntegrity(await (await fetch(esmsUrl)).text());

let html = `
<!doctype html>
<script type="module">
  import 'react';
</script>
`;
let pins = await generator.addMappings(html);

assert.strictEqual(await generator.htmlInject(html, { pins, integrity: true }),
  "\n" +
  "<!doctype html>\n" +
  "<!-- Generated by @jspm/generator - https://github.com/jspm/generator -->\n" +
  `<script async src="${esmsUrl}" crossorigin="anonymous" integrity="${esmsIntegrity}"></script>\n` +
  '<script type="importmap">\n' +
  "{\n" +
  '  "imports": {\n' +
  '    "react": "https://ga.jspm.io/npm:react@16.14.0/index.js"\n' +
  "  },\n" +
  '  "scopes": {\n' +
  '    "https://ga.jspm.io/": {\n' +
  '      "object-assign": "https://ga.jspm.io/npm:object-assign@4.1.1/index.js"\n' +
  "    }\n" +
  "  },\n" +
  '  "integrity": {\n' +
  '    "https://ga.jspm.io/npm:object-assign@4.1.1/index.js": "sha384-iQp1zoaqIhfUYyYkz3UNk1QeFfmBGgt1Ojq0kZD5Prql1g7fgJVzVgsjDoR65lv8",\n' +
  '    "https://ga.jspm.io/npm:react@16.14.0/cjs/react.production.min.js": "sha384-pTMZhybzHZ+1G029kWUmoGvTrBp1C+2oJAkZV48BBq7+e6Hk3bGuXtvxT2vQfBqj",\n' +
  '    "https://ga.jspm.io/npm:react@16.14.0/index.js": "sha384-jVagjV+2YtlseazU2byX6gMLPHaA5Ps2c6HhvsGDlWjn45YCCoU1q+QtQTOb1MjT"\n' +
  "  }\n" +
  "}\n" +
  "</script>\n" +
  '<script type="module">\n' +
  "  import 'react';\n" +
  "</script>\n"
);

// Idempotency
html = "\n" +
      "<!doctype html>\n" +
      "<!-- Generated by @jspm/generator - https://github.com/jspm/generator -->\n" +
      `<script async src="${esmsUrl}"></script>\n` +
      '<script type="importmap">\n' +
      "{\n" +
      '  "imports": {\n' +
      '    "react": "https://ga.jspm.io/npm:react@16.14.0/index.js"\n' +
      "  },\n" +
      '  "scopes": {\n' +
      '    "https://ga.jspm.io/": {\n' +
      '      "object-assign": "https://ga.jspm.io/npm:object-assign@4.1.1/index.js"\n' +
      "    }\n" +
      "  }\n" +
      "}\n" +
      "</script>\n" +
      '<link rel="modulepreload" href="https://ga.jspm.io/npm:object-assign@4.1.1/index.js" />\n' +
      '<link rel="modulepreload" href="https://ga.jspm.io/npm:react@16.14.0/index.js" />\n' +
      '<link rel="modulepreload" href="https://ga.jspm.io/npm:react@16.14.0/cjs/react.production.min.js" />\n' +
      '<script type="module">\n' +
      "  import 'react';\n" +
      "</script>\n";

pins = await generator.addMappings(html);

assert.strictEqual(await generator.htmlInject(html, { pins, preload: true, integrity: true, whitespace: false }),
  "\n" +
    "<!doctype html>\n" +
    "<!-- Generated by @jspm/generator - https://github.com/jspm/generator -->\n" +
    `<script async src="${esmsUrl}" crossorigin="anonymous" integrity="${esmsIntegrity}"></script>\n` +
    '<script type="importmap">{"imports":{"react":"https://ga.jspm.io/npm:react@16.14.0/index.js"},"scopes":{"https://ga.jspm.io/":{"object-assign":"https://ga.jspm.io/npm:object-assign@4.1.1/index.js"}},"integrity":{"https://ga.jspm.io/npm:object-assign@4.1.1/index.js":"sha384-iQp1zoaqIhfUYyYkz3UNk1QeFfmBGgt1Ojq0kZD5Prql1g7fgJVzVgsjDoR65lv8","https://ga.jspm.io/npm:react@16.14.0/cjs/react.production.min.js":"sha384-pTMZhybzHZ+1G029kWUmoGvTrBp1C+2oJAkZV48BBq7+e6Hk3bGuXtvxT2vQfBqj","https://ga.jspm.io/npm:react@16.14.0/index.js":"sha384-jVagjV+2YtlseazU2byX6gMLPHaA5Ps2c6HhvsGDlWjn45YCCoU1q+QtQTOb1MjT"}}</script>\n' +
    '<link rel="modulepreload" href="https://ga.jspm.io/npm:object-assign@4.1.1/index.js" /><link rel="modulepreload" href="https://ga.jspm.io/npm:react@16.14.0/cjs/react.production.min.js" /><link rel="modulepreload" href="https://ga.jspm.io/npm:react@16.14.0/index.js" />\n' +
    '<script type="module">\n' +
    "  import 'react';\n" +
    "</script>\n"
);
