import { Generator } from "@jspm/generator";
import assert from "assert";
import { SemverRange } from "sver";
import { getIntegrity } from "../../lib/common/integrity.js";

const generator = new Generator({
  mapUrl: new URL("./local/page.html", import.meta.url),
  env: ["production", "browser"],
});

const esmsPkg = await generator.traceMap.resolver.resolveLatestTarget(
  { name: "es-module-shims", registry: "npm", ranges: [new SemverRange("*")] },
  generator.traceMap.installer.defaultProvider
);
const esmsUrl =
  (await generator.traceMap.resolver.pkgToUrl(
    esmsPkg,
    generator.traceMap.installer.defaultProvider
  )) + "dist/es-module-shims.js";
const esmsIntegrity = await getIntegrity(await (await fetch(esmsUrl)).text());

let html = `
<!doctype html>
<script type="module">
  import 'react';
</script>
`;
let pins = await generator.addMappings(html);

const reactProductionIntegrity = await getIntegrity(
  await (
    await fetch(
      "https://ga.jspm.io/npm:react@16.14.0/cjs/react.production.min.js"
    )
  ).text()
);
const reactIndexIntegrity = await getIntegrity(
  await (await fetch("https://ga.jspm.io/npm:react@16.14.0/index.js")).text()
);

assert.strictEqual(
  await generator.htmlInject(html, { pins, integrity: true }),
  "\n" +
    "<!doctype html>\n" +
    "<!-- Generated by @jspm/generator - https://github.com/jspm/generator -->\n" +
    `<script async src="${esmsUrl}" crossorigin="anonymous" integrity="${esmsIntegrity}"></script>\n` +
    '<script type="importmap">\n' +
    "{\n" +
    '  "imports": {\n' +
    '    "react": "https://ga.jspm.io/npm:react@16.14.0/index.js"\n' +
    "  },\n" +
    '  "scopes": {\n' +
    '    "https://ga.jspm.io/": {\n' +
    '      "object-assign": "https://ga.jspm.io/npm:object-assign@4.1.1/index.js"\n' +
    "    }\n" +
    "  },\n" +
    '  "integrity": {\n' +
    '    "https://ga.jspm.io/npm:object-assign@4.1.1/index.js": "sha384-iQp1zoaqIhfUYyYkz3UNk1QeFfmBGgt1Ojq0kZD5Prql1g7fgJVzVgsjDoR65lv8",\n' +
    `    "https://ga.jspm.io/npm:react@16.14.0/cjs/react.production.min.js": "${reactProductionIntegrity}",\n` +
    `    "https://ga.jspm.io/npm:react@16.14.0/index.js": "${reactIndexIntegrity}"\n` +
    "  }\n" +
    "}\n" +
    "</script>\n" +
    '<script type="module">\n' +
    "  import 'react';\n" +
    "</script>\n"
);

// Idempotency
html =
  "\n" +
  "<!doctype html>\n" +
  "<!-- Generated by @jspm/generator - https://github.com/jspm/generator -->\n" +
  `<script async src="${esmsUrl}"></script>\n` +
  '<script type="importmap">\n' +
  "{\n" +
  '  "imports": {\n' +
  '    "react": "https://ga.jspm.io/npm:react@16.14.0/index.js"\n' +
  "  },\n" +
  '  "scopes": {\n' +
  '    "https://ga.jspm.io/": {\n' +
  '      "object-assign": "https://ga.jspm.io/npm:object-assign@4.1.1/index.js"\n' +
  "    }\n" +
  "  }\n" +
  "}\n" +
  "</script>\n" +
  '<link rel="modulepreload" href="https://ga.jspm.io/npm:object-assign@4.1.1/index.js" />\n' +
  '<link rel="modulepreload" href="https://ga.jspm.io/npm:react@16.14.0/index.js" />\n' +
  '<link rel="modulepreload" href="https://ga.jspm.io/npm:react@16.14.0/cjs/react.production.min.js" />\n' +
  '<script type="module">\n' +
  "  import 'react';\n" +
  "</script>\n";

pins = await generator.addMappings(html);

assert.strictEqual(
  await generator.htmlInject(html, {
    pins,
    preload: true,
    integrity: true,
    whitespace: false,
  }),
  "\n" +
    "<!doctype html>\n" +
    "<!-- Generated by @jspm/generator - https://github.com/jspm/generator -->\n" +
    `<script async src="${esmsUrl}" crossorigin="anonymous" integrity="${esmsIntegrity}"></script>\n` +
    `<script type="importmap">{"imports":{"react":"https://ga.jspm.io/npm:react@16.14.0/index.js"},"scopes":{"https://ga.jspm.io/":{"object-assign":"https://ga.jspm.io/npm:object-assign@4.1.1/index.js"}},"integrity":{"https://ga.jspm.io/npm:object-assign@4.1.1/index.js":"sha384-iQp1zoaqIhfUYyYkz3UNk1QeFfmBGgt1Ojq0kZD5Prql1g7fgJVzVgsjDoR65lv8","https://ga.jspm.io/npm:react@16.14.0/cjs/react.production.min.js":"${reactProductionIntegrity}","https://ga.jspm.io/npm:react@16.14.0/index.js":"${reactIndexIntegrity}"}}</script>\n` +
    `<link rel="modulepreload" href="https://ga.jspm.io/npm:object-assign@4.1.1/index.js" integrity="sha384-iQp1zoaqIhfUYyYkz3UNk1QeFfmBGgt1Ojq0kZD5Prql1g7fgJVzVgsjDoR65lv8" /><link rel="modulepreload" href="https://ga.jspm.io/npm:react@16.14.0/cjs/react.production.min.js" integrity="${reactProductionIntegrity}" /><link rel="modulepreload" href="https://ga.jspm.io/npm:react@16.14.0/index.js" integrity="${reactIndexIntegrity}" />\n` +
    '<script type="module">\n' +
    "  import 'react';\n" +
    "</script>\n"
);
